#!/usr/bin/env node
/**
 * aiCRO landing hero data builder — zero deps.
 *
 *   node build-hero.mjs <demoWebsiteDir> <outFile>
 *   e.g. node build-hero.mjs demo/analysis/website assets/hero-data.js
 *
 * Reads the demo's annotations.json + site/<file> pages, inlines each page's
 * stylesheet (shadow DOM can't follow relative links), and emits a JS file:
 *   window.AICRO_HERO = { domain, pages:[{id,file,title,path,intro,notes,html}] }
 * which the landing's hero-browser runtime (assets/app.js) hydrates into a
 * shadow root with a scroll-synced guidance sidebar. Same data shape as
 * build-preview.mjs's AICRO_PAGES, so the runtime is a reskin of preview.js.
 *
 * Static, committed output — the landing has no build step at view time and
 * opens from file:// with zero network requests.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';

const args = process.argv.slice(2);
const dir = resolve(args[0] || 'demo/analysis/website');
const out = resolve(args[1] || 'assets/hero-data.js');
const die = (m) => { console.error('FAIL: ' + m); process.exit(1); };
const warn = (m) => console.error('warn: ' + m);

const annPath = join(dir, 'annotations.json');
if (!existsSync(annPath)) die('no annotations.json in ' + dir);
const ann = JSON.parse(readFileSync(annPath, 'utf8'));
if (!ann.pages?.length) die('annotations.json has no pages');

let problems = 0;
const pages = ann.pages.map((p) => {
  const f = join(dir, 'site', p.file);
  if (!existsSync(f)) die(`page file missing: site/${p.file}`);
  let html = readFileSync(f, 'utf8');

  // inline stylesheets so the shadow root renders styled
  html = html.replace(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g, (m, href) => {
    const cssPath = join(dir, 'site', dirname(p.file), href);
    if (!existsSync(cssPath)) { warn(`${p.file}: stylesheet not found: ${href}`); problems++; return ''; }
    return '<style>\n' + readFileSync(cssPath, 'utf8') + '\n</style>';
  });

  // cross-validate notes <-> data-note sections
  const inPage = [...html.matchAll(/data-note="([^"]+)"/g)].map((m) => m[1]);
  const inNotes = (p.notes || []).map((n) => n.section);
  for (const s of inNotes) if (!inPage.includes(s)) { warn(`${p.file}: note "${s}" has no section`); problems++; }
  for (const s of inPage) if (!inNotes.includes(s)) { warn(`${p.file}: section "${s}" has no note`); problems++; }

  /* resolve bookRef anchors → hrefs relative to the LANDING root (the hero is
     embedded in index.html at the repo root, so the demo book is here). */
  const bookBase = process.argv[4] || 'demo/analysis/book/index.html';
  const notes = (p.notes || []).map((n) => {
    const out = { ...n };
    if (n.bookRef) out.bookHref = bookBase + '#' + String(n.bookRef).replace(/^#/, '');
    return out;
  });

  return { id: p.id, file: p.file, title: p.title, path: p.path || '/' + p.file,
           intro: p.intro || null, notes, html };
});

const payload = ('window.AICRO_HERO = ' + JSON.stringify({ domain: ann.domain, pages }) + ';')
  .replace(/<\//g, '<\\/'); // so embedded </script> can't break the host page

writeFileSync(out, '/* generated by build-hero.mjs — do not edit; edit the demo + re-run */\n' + payload + '\n');
console.log(JSON.stringify({ out, bytes: Buffer.byteLength(payload), pages: pages.map((p) => `${p.title} (${p.notes.length} notes)`), problems }, null, 2));
if (problems) console.error(problems + ' problem(s) — fix the demo before shipping the hero.');
